completed assessment
learn-academy-2023-bravo/week-1-assessment-jameshlee1 pull request #1
Opened 2023-03-20 15:32 UTC by jameshlee1

# Submitting Week 1 Assessment

### ✅ Completed Files

Select the following as confirmation that the files in this repository are complete.

- [ ] Coding Challenges
- [ ] Coding Concepts
- [ ] Interview Questions

### 📝 Feedback

If you would like specific feedback on a particular problem please leave details here:

2023-03-21 22:27 UTC, Genemichael25 requested changes
James, this is a good start to the assessments however I am requesting changes for missing pseudocode in code challenges section, problems # 1 and 4 . Also, your files should be kept separately and there is no need to combine them all into one. You will start to run into issues in the future when we have different files in which you need to do different things such as testing. Please make the changes requested and you will want to push up on the same branch. If you have any questions, please don't hesitate to reach out and I can help guide you in the right direction.

2023-03-21 22:27 UTC, Genemichael25 commented on week-1-jl.js
> +// Pseudo code:
Missing pseudocode. What happens if the temp is below 212?

2023-03-21 22:27 UTC, Genemichael25 commented on week-1-jl.js
> +// Pseudo code: the question is asking for a code that will combine the two arrays and returning the length. I created a variable and used the concat method to merge the two arrays then console.log t
Great , I think this approach works perfectly for what you need and the pseudocode paints a clear picture before I even see the code.

2023-03-21 22:27 UTC, Genemichael25 commented on week-1-jl.js
> +
Missing pseudocode here.

2023-03-21 22:27 UTC, Genemichael25 commented on week-1-jl.js
> +
Nice find with the sort method! Can you take that function in the sort method and use arrow syntax instead?

2023-03-21 22:27 UTC, Genemichael25 commented on week-1-jl.js
> +// b) Verify and explain: the variable greeting = "Hello world!" for the console.log(greeting[4]) it is asking for the fourth index letter of the element in the array. Starting from "0" which in this
You are completely correct that we would get "o"! Just be careful when referencing index like fourth index because the fourth index would actually be index three since we start with 0.

2023-03-21 22:27 UTC, Genemichael25 commented on week-1-jl.js
> +// b) Verify and explain: const weekendDays = "saturday, sunday" for the console.log(weekendDays/toUpperCase()) it is taking the string and converting it to all uppercase letters. toUpperCase() is a
Is it taking the strings and converting them to uppercase?

2023-03-21 22:27 UTC, Genemichael25 commented on week-1-jl.js
> +// Researched answer: The logical AND (&&) (logical conjunction) operator for a set of boolean operands will be true if and only if all the operands are true. Otherwise it will be false.
Great job mentioning the logical operators! Are there any other?

2023-03-21 22:27 UTC, Genemichael25 commented on week-1-jl.js
> +// Researched answer: The indexOf() method returns the position of the first occurrence of a value in a string. The indexOf() method returns -1 if the value is not found.
Love that you mentioned this method and use it as an example! This is a great place to broaden your current understanding on the question. 💯

2023-03-23 17:34 UTC, jameshlee1 commented on week-1-jl.js
> +// b) Verify and explain: const weekendDays = "saturday, sunday" for the console.log(weekendDays/toUpperCase()) it is taking the string and converting it to all uppercase letters. toUpperCase() is a
no this is taking the array not the string it is undefined or error

2023-03-23 22:47 UTC, Genemichael25 approved these changes
Thank you for making those changes James! This currently displays a novice level of comprehension. Continue to work on your pseudocode to help you get to that next level. I would encourage you to consider refactoring some of the code challenges. With # 5, I would look at taking that function in the sort method and trying to use an arrow function. Great work, keep it up!

2023-03-23 23:07 UTC, merged